name: Deploy_Node_Application

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t povindu/flameztest .
      - name: Publish Image to docker hub
        run: docker push povindu/flameztest:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from the docker hub
        run: docker pull povindu/flameztest:latest
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name flamez-backend-container



  